name: juju-bundle
base: core20
summary: Juju plugin for easy bundle interactions
description: |
  Allows building a bundle as necessary and then deploying it. Also
  allows removing an existing bundle without touching the other
  applications in a given model.

grade: stable
confinement: classic
adopt-info: juju-bundle

apps:
  juju-bundle:
    command: bin/juju-bundle

parts:
  juju-bundle:
    source: .
    plugin: rust
    # https://forum.snapcraft.io/t/issue-with-rebuilding-a-rust-snap/10830
    override-build: |
      [ -f "$SNAPCRAFT_PART_INSTALL/bin/juju-bundle" ] && rm "$SNAPCRAFT_PART_INSTALL/bin/juju-bundle"
      snapcraftctl build
      VERSION=$($SNAPCRAFT_PART_INSTALL/bin/juju-bundle --version | cut -d' ' -f2)
      snapcraftctl set-version $VERSION

architectures:
  - amd64
  - arm64
