name: juju-bundle
base: core20
summary: Juju plugin for easy bundle interactions
description: |
  See github repository for further information:

  https://github.com/knkski/juju-bundle
grade: stable
confinement: classic
adopt-info: juju-bundle
license: GPL-3.0

apps:
  juju-bundle:
    command: bin/juju-bundle

parts:
  juju-bundle:
    source: .
    plugin: rust
    override-build: |
      snapcraftctl build
      VERSION=$($SNAPCRAFT_PART_INSTALL/bin/juju-bundle --version | cut -d' ' -f2)
      snapcraftctl set-version $VERSION

architectures:
  - amd64
  - arm64
